# =========================
# Build stage
# =========================
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

# Copy solution
COPY BookStore.slnx ./

# Copy source
COPY src ./src

# Restore IdentityService
RUN dotnet restore \
    src/Services/IdentityService/BookStore.IdentityService.Api/BookStore.IdentityService.Api.csproj

# Build
RUN dotnet build \
    src/Services/IdentityService/BookStore.IdentityService.Api/BookStore.IdentityService.Api.csproj \
    --configuration Release  --no-restore

# Publish
RUN dotnet publish \
    src/Services/IdentityService/BookStore.IdentityService.Api/BookStore.IdentityService.Api.csproj \
    --configuration Release --no-build --output /app/publish


# =========================
# Runtime stage
# =========================
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final

RUN apt-get update \
    && apt-get install -y --no-install-recommends libgssapi-krb5-2 \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080

ENTRYPOINT ["dotnet", "BookStore.IdentityService.Api.dll"]
