services:

  postgres:
    image: postgres:17
    container_name: bookstore-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "5050:80"

    depends_on:
      - postgres


  rabbitmq:
    image: rabbitmq:4-management
    container_name: bookstore-rabbitmq
    restart: unless-stopped

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

    ports:
      - "5672:5672"
      - "15672:15672"

    networks:
      - bookstore-network



  redis:
    image: redis:7-alpine
    container_name: bookstore-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    networks:
      - bookstore-network

  jaeger:
   image: jaegertracing/all-in-one:latest
   container_name: bookstore-jaeger
   restart: unless-stopped
   ports:
    - "16686:16686"
    - "4317:4317"
    - "4318:4318"


volumes:

  postgres_data:

  redis_data:


networks:

  bookstore-network:
    driver: bridge

