# =========================
# Build stage
# =========================
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

# Copy solution
COPY BookStore.slnx ./

# Copy source
COPY src ./src

# Restore NotificationService
RUN dotnet restore src/Services/NotificationService/BookStore.NotificationService.csproj

# Build
RUN dotnet build src/Services/NotificationService/BookStore.NotificationService.csproj \
    --configuration Release --no-restore

# Publish
RUN dotnet publish src/Services/NotificationService/BookStore.NotificationService.csproj \
    --configuration Release --no-build  --output /app/publish


# =========================
# Runtime stage
# =========================
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "BookStore.NotificationService.dll"]
