<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BookStore.IdentityService.Application\BookStore.IdentityService.Application.csproj" />
    <ProjectReference Include="..\BookStore.IdentityService.Domain\BookStore.IdentityService.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
