<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookStore.IdentityService.Application\BookStore.IdentityService.Application.csproj" />
    <ProjectReference Include="..\BookStore.IdentityService.Infrastructure\BookStore.IdentityService.Infrastructure.csproj" />
    <ProjectReference Include="..\BookStore.IdentityService.Contracts\BookStore.IdentityService.Contracts.csproj" />
  </ItemGroup>

</Project>
